<script lang="ts">let { data, form } = $props(); const config = $derived(data.management?.form)</script>
<svelte:head><title>Adhésions familiales</title></svelte:head>
<main class="space-y-8 p-6"><h1 class="text-3xl font-bold">Adhésions familiales</h1>{#if form?.error}<p class="text-red-700">{form.error}</p>{/if}
{#if config}<section><h2 class="text-xl font-semibold">Configuration</h2><form method="POST" action="?/configuration" class="grid max-w-xl gap-3">
<input type="hidden" name="revision" value={config.revision}/><label>Titre <input name="title" value={config.title}/></label><label>Introduction <textarea name="intro">{config.intro ?? ''}</textarea></label><label>Texte de consentement <textarea name="consentLabel">{config.consentLabel ?? ''}</textarea></label>
<label>Tarif en centimes CHF <input type="number" name="annualFeeCents" value={config.annualFeeCents}/></label><label>Membres maximum <input type="number" name="maxMembers" value={config.maxMembers}/></label><label>Rétention après traitement (jours) <input type="number" name="retentionDays" value={config.retentionDays}/></label>
<label><input type="checkbox" name="allowsTwint" checked={config.allowsTwint}/> TWINT sur place</label><label><input type="checkbox" name="allowsCash" checked={config.allowsCash}/> Espèces sur place</label><label><input type="checkbox" name="enabled" checked={config.enabled}/> Formulaire actif</label><button>Enregistrer</button></form>
<form method="POST" action="?/publish"><input type="hidden" name="formId" value={config.id}/><input type="hidden" name="revision" value={config.revision}/><button>Publier une version</button></form></section>
<section><h2 class="text-xl font-semibold">Documents existants</h2>{#each data.management?.documents ?? [] as document}<form method="POST" action="?/document" class="grid max-w-xl gap-2 rounded border p-3"><input type="hidden" name="id" value={document.id}/><input type="hidden" name="revision" value={document.revision}/><input required name="title" value={document.title}/><select name="kind" value={document.kind}><option value="rules">Règlement</option><option value="contract">Contrat</option><option value="privacy">Confidentialité</option><option value="other">Autre</option></select><label><input type="checkbox" name="requiredAcceptance" checked={document.requiredAcceptance}/> Acceptation obligatoire</label><input type="number" name="sortOrder" value={document.sort_order}/><textarea required name="contentMarkdown">{document.content_markdown ?? ''}</textarea><button>Créer une nouvelle version</button></form>{/each}</section>
<section><h2 class="text-xl font-semibold">Ajouter un document</h2><form method="POST" action="?/document" class="grid max-w-xl gap-3"><input required name="slug" placeholder="reglement"/><input required name="title" placeholder="Titre"/><select name="kind"><option value="rules">Règlement</option><option value="contract">Contrat</option><option value="privacy">Confidentialité</option><option value="other">Autre</option></select><label><input type="checkbox" name="requiredAcceptance" checked/> Acceptation obligatoire</label><input type="number" name="sortOrder" value="0"/><textarea required name="contentMarkdown" placeholder="Contenu validé par la ludothèque"></textarea><button>Créer et versionner</button></form></section>{/if}
<section><h2 class="text-xl font-semibold">Demandes</h2><table><thead><tr><th>Créée</th><th>Responsable</th><th>Statut</th><th>Paiement</th><th>Actions</th></tr></thead><tbody>{#each data.submissions as item}<tr><td>{new Date(item.createdAt).toLocaleDateString('fr-CH')}</td><td><a href={`?id=${item.id}`}>{item.firstName} {item.lastName}</a></td><td>{item.status}</td><td>{item.paymentMethod ?? 'Non enregistré'}</td><td>{#if item.status === 'new'}<form class="inline" method="POST" action="?/process"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="revision" value={item.revision}/><button>Marquer traitée</button></form>{:else}<form class="inline" method="POST" action="?/payment"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="revision" value={item.revision}/><select name="method"><option value="">Non payé</option><option value="twint">TWINT</option><option value="cash">Espèces</option></select><button>Enregistrer paiement</button></form>{/if}</td></tr>{/each}</tbody></table></section>
{#if data.selected}<section class="space-y-2 rounded border p-4"><h2 class="text-xl font-semibold">Détail de la demande</h2><p>{data.selected.firstName} {data.selected.lastName} — {data.selected.email} — {data.selected.phone}</p><p>{data.selected.address}, {data.selected.postalCode} {data.selected.city}</p><p>Consentement : {data.selected.consentFullName}, le {data.selected.consentAcceptedOn}</p><h3 class="font-semibold">Membres</h3><ul>{#each data.selected.members as member}<li>{member.firstName} {member.lastName}{member.birthDate ? ` — ${member.birthDate}` : ''}</li>{/each}</ul></section>{/if}</main>
